// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WeeklyPlanTracker.Infrastructure.Data;

#nullable disable

namespace WeeklyPlanTracker.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260302110446_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WeeklyPlanTracker.Core.Entities.BacklogItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("EstimatedHours")
                        .HasColumnType("int");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("BacklogItems");
                });

            modelBuilder.Entity("WeeklyPlanTracker.Core.Entities.PlanAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BacklogItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CommittedHours")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("HoursCompleted")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid>("TeamMemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WeeklyPlanId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BacklogItemId");

                    b.HasIndex("TeamMemberId");

                    b.HasIndex("WeeklyPlanId", "TeamMemberId", "BacklogItemId")
                        .IsUnique();

                    b.ToTable("PlanAssignments");
                });

            modelBuilder.Entity("WeeklyPlanTracker.Core.Entities.ProgressUpdate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("HoursDone")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("PlanAssignmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PlanAssignmentId");

                    b.ToTable("ProgressUpdates");
                });

            modelBuilder.Entity("WeeklyPlanTracker.Core.Entities.TeamMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("TeamMembers");
                });

            modelBuilder.Entity("WeeklyPlanTracker.Core.Entities.WeeklyPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ClientFocusedPercent")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PlanningDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RAndDPercent")
                        .HasColumnType("int");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("TechDebtPercent")
                        .HasColumnType("int");

                    b.Property<DateTime>("WorkEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("WorkStartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("State");

                    b.ToTable("WeeklyPlans");
                });

            modelBuilder.Entity("WeeklyPlanTracker.Core.Entities.WeeklyPlanMember", b =>
                {
                    b.Property<Guid>("WeeklyPlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TeamMemberId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("WeeklyPlanId", "TeamMemberId");

                    b.HasIndex("TeamMemberId");

                    b.ToTable("WeeklyPlanMembers");
                });

            modelBuilder.Entity("WeeklyPlanTracker.Core.Entities.PlanAssignment", b =>
                {
                    b.HasOne("WeeklyPlanTracker.Core.Entities.BacklogItem", "BacklogItem")
                        .WithMany("PlanAssignments")
                        .HasForeignKey("BacklogItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WeeklyPlanTracker.Core.Entities.TeamMember", "TeamMember")
                        .WithMany("PlanAssignments")
                        .HasForeignKey("TeamMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WeeklyPlanTracker.Core.Entities.WeeklyPlan", "WeeklyPlan")
                        .WithMany("PlanAssignments")
                        .HasForeignKey("WeeklyPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BacklogItem");

                    b.Navigation("TeamMember");

                    b.Navigation("WeeklyPlan");
                });

            modelBuilder.Entity("WeeklyPlanTracker.Core.Entities.ProgressUpdate", b =>
                {
                    b.HasOne("WeeklyPlanTracker.Core.Entities.PlanAssignment", "PlanAssignment")
                        .WithMany("ProgressUpdates")
                        .HasForeignKey("PlanAssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlanAssignment");
                });

            modelBuilder.Entity("WeeklyPlanTracker.Core.Entities.WeeklyPlanMember", b =>
                {
                    b.HasOne("WeeklyPlanTracker.Core.Entities.TeamMember", "TeamMember")
                        .WithMany("WeeklyPlanMembers")
                        .HasForeignKey("TeamMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WeeklyPlanTracker.Core.Entities.WeeklyPlan", "WeeklyPlan")
                        .WithMany("WeeklyPlanMembers")
                        .HasForeignKey("WeeklyPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TeamMember");

                    b.Navigation("WeeklyPlan");
                });

            modelBuilder.Entity("WeeklyPlanTracker.Core.Entities.BacklogItem", b =>
                {
                    b.Navigation("PlanAssignments");
                });

            modelBuilder.Entity("WeeklyPlanTracker.Core.Entities.PlanAssignment", b =>
                {
                    b.Navigation("ProgressUpdates");
                });

            modelBuilder.Entity("WeeklyPlanTracker.Core.Entities.TeamMember", b =>
                {
                    b.Navigation("PlanAssignments");

                    b.Navigation("WeeklyPlanMembers");
                });

            modelBuilder.Entity("WeeklyPlanTracker.Core.Entities.WeeklyPlan", b =>
                {
                    b.Navigation("PlanAssignments");

                    b.Navigation("WeeklyPlanMembers");
                });
#pragma warning restore 612, 618
        }
    }
}
